### ISSUE TITLE
iOS build failed when use yandex-mapkit-kmp-compose:0.0.2

### ISSUE THREAD

**Issue by catron** [SuLG-ik/yandex-mapkit-kmp#7] opened 2024-07-27 09:45 UTC
The error is reproduced on the sample project, when use implementation("ru.sulgik.mapkit:yandex-mapkit-kmp-compose:0.0.2")

error: org.jetbrains.kotlin.backend.konan.llvm.NativeCodeGeneratorException: Exception during generating code for following declaration:
Inside: FILE fqName:ru.sulgik.mapkit.sample fileName:/Users/evgeniypavlov/ProjectsFolder/yandex-mapkit-kmp-main 2/sample/composeApp/src/commonMain/kotlin/ru/sulgik/mapkit/sample/Map.kt
@Composable
private fun MapScreen$lambda$8($mapController: YandexMapController, /* var */ $composer: Composer?, $changed: Int) {
  var $composer: Composer? = $composer
  when {
    when {
      areEqualByValue(first = $changed.and(other = 11).reinterpret<Int, Int>(), second = 2.reinterpret<Int, Int>()).not() -> true
      true -> $composer.<get-skipping>().not()
    } -> { // BLOCK
      MapActions(mapController = $mapController, modifier = <get-$companion>().fillMaxWidth$default(fraction = // COMPOSITE {
      0.0F.reinterpret<Float, Float>()
      // }, $mask0 = 1), $composer = $composer, $changed = 48.or(other = #ru_sulgik_mapkit_compose_YandexMapController$stable), $default = 0)
    }
    true -> $composer.skipToGroupEnd()
  }
  return theUnitInstance()
}

**Comment by SuLG-ik** [comment] 2024-07-27 10:13
Thanks, for your report. I reproduced this bug and find the solution. This is not a bug in my library, it's Kotlin 2.0 bug. You can track it here https://youtrack.jetbrains.com/issue/CMP-4809.
Now, you can fix it by adding the following lines to your `gradle.properties` file:
```
kotlin.native.cacheKind=none
compose.kotlin.native.manageCacheKind=false
``` 
I would keep your issue until this bug will not be fixed by stable Kotlin version or finding another way to fix this bug.

**Closed** 2024-08-17 08:18 UTC
Labels: bug
